require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  SuggestExtensions: false

Lint/RedundantCopDisableDirective:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"
    - "config.ru"
    - "package.json"
    - "*.yml"
    - "*.md"

Layout/EndOfLine:
  EnforcedStyle: lf
  AutoCorrect: true

Layout/LineLength:
  Max: 125
  AllowHeredoc: true
  AllowURI: true

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 150

RSpec:
  Enabled: true

  MultipleExpectations:
    Enabled: false

  MultipleMemoizedHelpers:
    Max: 10

  ExampleLength:
    Max: 10

  ContextWording:
    Enabled: false

  ContextLength:
    Max: 10
