require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  SuggestExtensions: false

Lint/RedundantCopDisableDirective:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"
    - "config.ru"
    - "package.json"
    - "*.yml"
    - "*.md"

Layout/EndOfLine:
  EnforcedStyle: lf
  AutoCorrect: true

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true

Metrics/MethodLength:
  Max: 20  # Relaxed from 15 to 20 to allow for more complex methods

Metrics/AbcSize:
  Max: 15  # Increased from 10 to 15 to accommodate more complex logic

Metrics/ClassLength:
  Max: 150  # Increased from 100 to 150 to allow for larger classes, especially in Rails

RSpec:
  Enabled: true

  # Allows for more flexibility in writing tests
  MultipleExpectations:
    Enabled: false

  # Increase the max allowed memoized helpers
  MultipleMemoizedHelpers:
    Max: 8  # Increase this to 8 or more if needed

  # Allows for longer test examples when necessary
  ExampleLength:
    Max: 10  # Increase this if your examples are too long

  ContextWording:
    Enabled: false  # You can disable this if you don't want to follow the specific wording rules

  # Allows for more flexibility in context blocks
  ContextLength:
    Max: 10  # Increase this to allow for more lines in your context blocks
