name: "Run Tests and Upload Coverage"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Ruby environment
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    # Step 4: Run tests with SimpleCov for coverage and generate RSpec results
    - name: Run tests and generate coverage
      run: |
        echo "${{ secrets.PHCDEV_TEST_KEY }}" > spec/dummy/config/master.key
        mkdir -p tmp
        # Start SimpleCov before running tests
        bundle exec rspec --require simplecov --format json --out tmp/rspec_results.json

    # Step 5: Upload RSpec test results (test analytics)
    - name: Upload RSpec test results
      uses: actions/upload-artifact@v3
      with:
        name: rspec-results
        path: tmp/rspec_results.json

    # Step 6: Upload coverage to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/.resultset.json
        token: ${{ secrets.CODECOV_TOKEN }}

    # Step 7: Upload coverage report artifact (optional for debugging)
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
