name: Run RSpec Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.3.4']
    steps:
    # Step 1: Check out the repository
    - name: Check out repository code
      uses: actions/checkout@v3

    # Step 2: Set up Ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    # Step 3: Install dependencies with verbose logging
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --verbose

    # Step 4: Set up testing key
    - name: Set up key for testing
      run: |
        echo "${{ secrets.PHCDEV_TEST_KEY }}" > spec/dummy/config/master.key

    # Step 6: Run tests
    - name: Run tests
      run: |
        bundle exec rspec --backtrace
